server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: servicesExchange
  queue:
    paymentStatusUpdate: paymentStatusUpdateQueue
    orderExistence: orderExistenceQueue
  routingKey:
    paymentStatusUpdate: paymentStatusUpdateRoutingKey
    orderExistence: orderExistenceRoutingKey